# Generated by Django 6.1.1 on 2026-09-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeCutoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("EWS", "EWS"),
                            ("OBC_NCL", "OBC-NCL"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("FEMALE", "Female")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("home_state", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("opening_rank", models.PositiveIntegerField()),
                ("closing_rank", models.PositiveIntegerField()),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutoffs",
                        to="colleges.branch",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutoffs",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "ordering": ["closing_rank"],
            },
        ),
    ]
