# Generated by Django 6.1.1 on 2026-09-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_careerrecommendation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("career", models.CharField(max_length=200)),
                ("current_level", models.CharField(default="Beginner", max_length=100)),
                ("missing_skills", models.TextField(blank=True)),
                ("recommended_skills", models.TextField(blank=True)),
                ("projects", models.TextField(blank=True)),
                ("roadmap", models.TextField(blank=True)),
                ("duration_months", models.PositiveIntegerField(default=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
